export const ADD_MESSAGE_FAILED = 'ADD_MESSAGE_FAILED';
export const ADD_MESSAGE_REQUESTED = 'ADD_MESSAGE_REQUESTED';
export const ADD_MESSAGE_SUCCEEDED = 'ADD_MESSAGE_SUCCEEDED';

export const FILTER_CHANGED = 'FILTER_CHANGED';

export const FORM_CHANGED = 'FORM_CHANGED';

export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';
export const GET_MESSAGES_REQUESTED = 'GET_MESSAGES_REQUESTED';
export const GET_MESSAGES_SUCCEEDED = 'GET_MESSAGES_SUCCEEDED';
